/*
 * Copyright (C) 2015 banjum
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.ghc.foss.frames;
import com.ghc.foss.ds.*;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author banjum
 */
public class Visualizer extends javax.swing.JFrame {
    
    /**
     * Creates new form Visualizer
     */
    public Visualizer(DataStructure ds, String name, Boolean requiresRemoveKey, javax.swing.JFrame mf) {
        mainframe=mf;
        initComponents();
        structure = ds;
        jLabelDSName.setText("Visualizing A "+name);
        jTextAreaDisplay.setText("Add a value to visualize");
        if (!requiresRemoveKey)
        {
            jTextFieldRemove.setBackground(Color.LIGHT_GRAY);
            jTextFieldRemove.setEnabled(false);
        }
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDSName = new javax.swing.JLabel();
        jTextFieldAdd = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldRemove = new javax.swing.JTextField();
        jButtonRemove = new javax.swing.JButton();
        Empty = new javax.swing.JButton();
        jPanelDisplayArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();
        Random = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DS Visualizer");

        jLabelDSName.setText("jLabel1");

        jTextFieldAdd.setAutoscrolls(false);
        jTextFieldAdd.setName("Add value"); // NOI18N

        jButtonAdd.setText("Add");
        jButtonAdd.setMaximumSize(new java.awt.Dimension(70, 23));
        jButtonAdd.setMinimumSize(new java.awt.Dimension(70, 23));
        jButtonAdd.setPreferredSize(new java.awt.Dimension(70, 23));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldRemove.setAutoscrolls(false);

        jButtonRemove.setText("Remove");
        jButtonRemove.setMaximumSize(new java.awt.Dimension(70, 23));
        jButtonRemove.setMinimumSize(new java.awt.Dimension(70, 23));
        jButtonRemove.setPreferredSize(new java.awt.Dimension(70, 23));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        Empty.setText("Empty");
        Empty.setMaximumSize(new java.awt.Dimension(70, 23));
        Empty.setMinimumSize(new java.awt.Dimension(70, 23));
        Empty.setPreferredSize(new java.awt.Dimension(70, 23));
        Empty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmptyActionPerformed(evt);
            }
        });

        jPanelDisplayArea.setAutoscrolls(true);

        jTextAreaDisplay.setEditable(false);
        jTextAreaDisplay.setBackground(new java.awt.Color(204, 204, 255));
        jTextAreaDisplay.setColumns(30);
        jTextAreaDisplay.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jTextAreaDisplay.setRows(5);
        jTextAreaDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextAreaDisplay.setFocusable(false);
        jTextAreaDisplay.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        javax.swing.GroupLayout jPanelDisplayAreaLayout = new javax.swing.GroupLayout(jPanelDisplayArea);
        jPanelDisplayArea.setLayout(jPanelDisplayAreaLayout);
        jPanelDisplayAreaLayout.setHorizontalGroup(
            jPanelDisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
            .addGroup(jPanelDisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE))
        );
        jPanelDisplayAreaLayout.setVerticalGroup(
            jPanelDisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(jPanelDisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Random.setText("Add 10");
        Random.setMaximumSize(new java.awt.Dimension(70, 23));
        Random.setMinimumSize(new java.awt.Dimension(70, 23));
        Random.setPreferredSize(new java.awt.Dimension(70, 23));
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDSName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Empty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Random, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jPanelDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDSName)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(Random, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Empty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        //Removing requires a key value (tree)
        if(jTextFieldRemove.isEnabled())
        {
            String input = jTextFieldRemove.getText().trim();
            jTextFieldRemove.setText("");
            if(input.length()==0)
                JOptionPane.showMessageDialog(this, "Please enter a value to be removed");
            else
            {
                if(!structure.remove(Integer.parseInt(input)))
                    JOptionPane.showMessageDialog(this, "Unable to find/delete "+input);
            
                display();
            }
        }
        else //Removing does not require a key value (stack, queue, heap)
        {
            structure.remove(0);//sending dummy parameter
            display();
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String input = jTextFieldAdd.getText().trim();
        jTextFieldAdd.setText("");
        if(input.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Please enter a value to be added");
        }
        else
        {
            structure.add(Integer.parseInt(input));
            display();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void EmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmptyActionPerformed
        structure.removeAll();
        display();
    }//GEN-LAST:event_EmptyActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        mainframe.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        structure.addRandomValues();
        display();
    }//GEN-LAST:event_RandomActionPerformed

    private void display()
    {
        String displayString=structure.getDisplayString(jTextAreaDisplay.getColumns());
        jTextAreaDisplay.setText(displayString);
        jPanelDisplayArea.validate();

    }
    
    // Data Structure
    DataStructure structure;
    
    // Reference to Main frame
    private final javax.swing.JFrame mainframe;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Empty;
    private javax.swing.JButton Random;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabelDSName;
    private javax.swing.JPanel jPanelDisplayArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JTextField jTextFieldAdd;
    private javax.swing.JTextField jTextFieldRemove;
    // End of variables declaration//GEN-END:variables
}
